version: "3"

services:
  nonebot:
    build: .
    expose:
      - 8080
    volumes:
      - ./questions.db:/questions.db
    environment:
      - TZ=Asia/Shanghai

  gocqhttp:
    image: pcrbot/gocqhttp:latest
    volumes:
      - ./go-cqhttp:/data:delegated
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - nonebot
